[CmdletBinding()]
param(
    [string]$SettingsPath,
    [string]$SourceDirectory,
    [string]$DestinationDirectory,
    [switch]$AllowRunningSnapshot,
    [switch]$Watch
)
$ErrorActionPreference = 'Stop'
function Read-MigrationSettings {
    if (-not $SettingsPath) { return $null }
    $value = Get-Content -LiteralPath $SettingsPath -Raw | ConvertFrom-Json
    $script:SourceDirectory = $value.SourceProfileDirectory
    $script:DestinationDirectory = $value.ProfileDirectory
    return $value
}
function Test-ProfileInUse([string]$ProfilePath) {
    $normalized = $ProfilePath.Replace('/', '\').TrimEnd('\')
    @(Get-CimInstance Win32_Process -Filter "Name='ChatGPT.exe' OR Name='Codex.exe'" | Where-Object {
        $_.CommandLine -and
        $_.CommandLine.Replace('/', '\').IndexOf($normalized, [StringComparison]::OrdinalIgnoreCase) -ge 0
    }).Count -gt 0
}
$settings = Read-MigrationSettings
if (-not $SourceDirectory) { return }
$sourcePath = [IO.Path]::GetFullPath($SourceDirectory).TrimEnd('\')
$destinationPath = [IO.Path]::GetFullPath($DestinationDirectory).TrimEnd('\')
if ($sourcePath.Equals($destinationPath, [StringComparison]::OrdinalIgnoreCase) -or
    $destinationPath.StartsWith($sourcePath + '\', [StringComparison]::OrdinalIgnoreCase) -or
    $sourcePath.StartsWith($destinationPath + '\', [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Profile migration requires separate, non-nested source and destination directories.'
}
if (-not (Test-Path -LiteralPath $sourcePath -PathType Container)) {
    throw "The previous profile is unavailable: $sourcePath"
}
if ($Watch) {
    while (Test-ProfileInUse $sourcePath) { Start-Sleep -Seconds 2 }
} elseif (-not $AllowRunningSnapshot -and (Test-ProfileInUse $sourcePath)) {
    throw 'Finish the running Codex tasks and fully quit the app before completing profile migration.'
}
$hashProvider = [Security.Cryptography.SHA256]::Create()
try { $hash = [BitConverter]::ToString($hashProvider.ComputeHash([Text.Encoding]::UTF8.GetBytes($destinationPath.ToLowerInvariant()))).Replace('-', '') }
finally { $hashProvider.Dispose() }
$mutex = New-Object Threading.Mutex($false, ('Local\CodexTheme.ProfileMigration.' + $hash))
$locked = $false
try {
    try { $locked = $mutex.WaitOne(60000) } catch [Threading.AbandonedMutexException] { $locked = $true }
    if (-not $locked) { throw 'Another profile migration is still in progress. Retry shortly.' }
    if ($SettingsPath) {
        $settings = Read-MigrationSettings
        if (-not $settings.SourceProfileDirectory) { return }
    }
    if (-not $AllowRunningSnapshot -and (Test-ProfileInUse $sourcePath)) {
        throw 'The previous Codex profile is still in use.'
    }
    if (Test-ProfileInUse $destinationPath) {
        throw 'The destination profile is in use. Fully quit that Codex instance before migrating.'
    }
    New-Item -ItemType Directory -Path $destinationPath -Force | Out-Null
    # Copy user state without deleting either profile. Process locks and caches
    # are regenerated by Chromium and must not be carried to the new location.
    $excludedFiles = @('LOCK', 'lockfile', 'Singleton*', 'BrowserMetrics*.pma')
    if ($AllowRunningSnapshot) { $excludedFiles += @('Cookies', 'Cookies-journal', 'Cookies-wal', 'Cookies-shm') }
    & robocopy.exe $sourcePath $destinationPath /E /XJ /R:0 /W:0 /NFL /NDL /NP /NJH /NJS `
        /XF $excludedFiles `
        /XD Cache 'Code Cache' GPUCache Crashpad ShaderCache GrShaderCache GPUPersistentCache 'Safe Browsing' sentry | Out-Null
    $copyExitCode = $LASTEXITCODE
    if ($copyExitCode -ge 8) { throw "Profile copy failed (robocopy exit $copyExitCode). The original profile is preserved." }
    if ($SettingsPath -and -not $AllowRunningSnapshot) {
        $settings.PSObject.Properties.Remove('SourceProfileDirectory')
        $settings | ConvertTo-Json | Set-Content -LiteralPath $SettingsPath -Encoding UTF8
    }
    Write-Output $(if ($AllowRunningSnapshot) { 'Profile snapshot copied; final synchronization will run when Codex closes.' } else { 'Profile migration completed.' })
} finally {
    if ($locked) { $mutex.ReleaseMutex() }
    $mutex.Dispose()
}
